/*

Types of Response in Enterprise Applications
============================================================

        a. Static Response
        b. Dynamic Response


Static Response
++++++++++++++

    Static response is the response in which the only responsibility of the server is to
    search for a particular resource requested by the client and give it back to the client.

    No code is executed at the server side as in case of servlets which will generate the
    dynamic response.



Dynamic Response
++++++++++++++++

    In the case of Dynamic response some code is executed at the server side.

    User submits the request in a form. Based upon the request dynamic response is generated 
    by server due to code written in the servlet.

    Example

        Lets say we have a calculator application on web which takes two inputs and based
    upon that  a response is generated. Now in this case depending upon the input the response
    is going to change, as in if the user is going to pass input as 10 and 20 then 30 will be 
    generated and if some other numbers are passed then different output will be generated.


a. User gives the input (add?val=10&val=20) and then based upon the inputs AddAction.java
   servlet is going to execute and a dynamic response will be generated based upon that.

b. Server will look for AddAction.java in server machine.

c. Response is generated by performing some coding at the server machine unlike simply just
   fetching the data stored in the server and giving it to the client as in the case of static response.

d. So here in the case of dynamic response , response changes depending upon the input which are given 
   by the user. This is made possible due to some code executed at the server machine done by the servlets.


To generate the dynamic response we have to execute an application at server side called as the web applications

                a. CGI
                b. Servlets
                c. JSPs





*/