/*

HTTP Request and Response Messages
==========================================

1. HTTP client and server communicate by sending text messages. The client sends a request message to the server.  
   The server, in turn, returns a response message.

2. An HTTP message consists of a message header and an optional message body, separated by a blank line, as illustrated below:


            ------------------------------
            |hhhhhhhhhhhhhhhhhhhhhhhhh    |    
            |hhhhhhhhhhhhhhhhhhhhhhhhh    |  ---->message header
            |hhhhhhhhhhhhhhhhhhhhhhhhhh   |
            |                             |  ----> blank line separating header and body.
            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  |  
            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  |  -------> message body.
            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  | 
            ------------------------------    

                    HTTP message.
                

3. The format of an HTTP request message is as follow:

        

            
                            ------------------------------
      ----request line      |hhhhhhhhhhhhhhhhhhhhhhhhh    |    
      ----request header1   |hhhhhhhhhhhhhhhhhhhhhhhhh    |  ----> request message header
      -----request header2  |hhhhhhhhhhhhhhhhhhhhhhhhhh   |
                            |                             |  ----> blank line separating header and body.
                            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  |  
                            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  |  -------> request message body(optional)
                            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  | 
                            ------------------------------    

                                    HTTP request message.



4. Request Line
================

The first line of the header is called the request line, followed by optional request headers.

The request line has the following syntax:

    request-method-name request-URI HTTP-version

    request-method-name: HTTP protocol defines a set of request methods, e.g., GET, POST, HEAD, and OPTIONS. 
                        The client can use one of these methods to send a request to the server.
    request-URI: specifies the resource requested.
    HTTP-version: Two versions are currently in use: HTTP/1.0 and HTTP/1.1.

Examples of request line are:

GET /test.html HTTP/1.1
HEAD /query.html HTTP/1.0
POST /index.html HTTP/1.1



5. Request Headers
===================

The request headers are in the form of name: value pairs. Multiple values, separated by commas, can be specified.

request-header-name: request-header-value1, request-header-value2, ...

Examples of request headers are:

Host: www.xyz.com
Connection: Keep-Alive
Accept: image/gif, image/jpeg, *
Accept-Language: us-en, fr, cn


Example

The following shows a sample HTTP request message:


GET/doc/test.html HTTP/1.1-----> request line
Host: www.test101.com  --------->request header1-----
Accept:image/gif, image/jpeg,----->request header2  |
Accept-Language:en-us------------->request header3  |---->Request Message header
Accept-Encoding:gzip, deflate----->request header4  |
User-Agent:Mozilla/4.0------------>request header5  |
Content-Length:35----------------->request header6--|

 --------blank line- separating header and the body----

bookId=12345&author=Tan+Ah+Teck         --------> request message body(optional)



                                                                    HTTP Response Message
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The format of the HTTP response message is as follows:


    
                            ------------------------------
      ----status line       |hhhhhhhhhhhhhhhhhhhhhhhhh    |    
      ----response header1  |hhhhhhhhhhhhhhhhhhhhhhhhh    |  ----> response message header
      -----response header2 |hhhhhhhhhhhhhhhhhhhhhhhhhh   |
                            |                             |  ----> blank line separating header and body.
                            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  |  
                            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  |  -------> response message body(optional)
                            |bbbbbbbbbbbbbbbbbbbbbbbbbbb  | 
                            ------------------------------    

                                    HTTP response message.




1. Status Line
==========================

The first line is called the status line, followed by optional response header(s).

The status line has the following syntax:

        HTTP-version status-code reason-phrase

    HTTP-version: 
        The HTTP version used in this session. Either HTTP/1.0 and HTTP/1.1.
    
    status-code: 
        a 3-digit number generated by the server to reflect the outcome of the request.
    
    reason-phrase: 
        gives a short explanation to the status code.
        Common status code and reason phrase are "200 OK", "404 Not Found", "403 Forbidden", "500 Internal Server Error".

Examples of status line are:

HTTP/1.1 200 OK
HTTP/1.0 404 Not Found
HTTP/1.1 403 Forbidden



2. Example

The following shows a sample response message:


HTTP/1.1 200 OK------------------------> Status Line--------------------------------
Date: Mon, 27 Jul 2009 12:28:53 GMT----------------                                 |
Server: Apache/2.2.14 (Win32)                      |                                |
Last-Modified: Wed, 22 Jul 2009 19:15:56 GMT       |--------response headers        |-->Response message header
Content-Length: 88                                 |                                |
Content-Type: text/html                            |                                |
Connection: Closed------------------------------------------------------------------

----blank line separating header and body

<h1> My Home Page</h1>----------------------------------------> Response message body

*/

