package Constructors;

/*

Default Constructors
=====================================

1. Compiler is responsible to generate default constructor( but not JVM).

2. If we are not writing any constructor then only compiler will generate default constructor.

3. That is if we write at least one constructor then compiler wont generate default constructor.

4. Hence every class in java can contain constructor it may be default constructor generated by compiler
   or customised constructor explicitly provided by the programmer but not both simultaneously.

5. If we are creating a class without a constructor, then by default a constructor will be given by the compiler.




Prototype of Default Constructor.
===========================================

1. It is always no argument constructor.

2. The access modifier of default constructor is exactly same as access modifier of 
   the class.( This rule is only applicable for public and default)

3. It contains only one line 

            super();
 
  It is no argument call to super class constructor.            


*/

//--------------------------------------------------------------------------*********--------------------------------------------------------------------------