package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCV06000 - if Third party Liability indicated, then")
internal class CCV06000ifThirdpartyLiabilityindicatedthen {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return (claim.FaultRating == "thirdparty" 
 or (claim.FaultRating == "1" and claim.Fault != 100 and claim.Fault != null))
and claim.SubrogationStatus == null
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
var ruleName = gw.api.util.StringUtil.substring(actions.getRule() as java.lang.String, 0, 8)
claim.reject("newloss",displaykey.Subrogation.Validation.ClaimClosed.NullSubroStatus(ruleName), null, null)
/*end00rule*/

  }
}
