package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCV01000 - Open exposures")
internal class CCV01000Openexposures {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return exists (exp in claim.Exposures
        where not (exp.State == "closed"))
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
claim.reject("newloss", displaykey.Rules.Validation.CloseClaim.CloseAllOpenExposures, null, null)
/*end00rule*/

  }
}
