package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EXV01000 - Incident not null")
internal class EXV01000Incidentnotnull {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.Incident == null
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
exposure.reject("loadsave", displaykey.Rules.Validation.Exposure.NoIncident, null, null)
/*end00rule*/

  }
}
