package rules.Validation.ExposureReopenedValidationRules_dir

@gw.rules.RuleName("ERV01000 - Claim closed")
internal class ERV01000Claimclosed {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.Claim.State <> "open"
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
exposure.reject("newloss", displaykey.Rules.Validation.ReopenExposure.OpenClaimRequired, null, null)
/*end00rule*/

  }
}
