package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CLV07000 -  Liability can not exceed 100")
internal class CLV07000Liabilitycannotexceed100 {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.SubrogationSummary != null 
and claim.SubrogationSummary.SubroAdverseParties.length > 0
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
var totalExpLiability : java.math.BigDecimal = claim.AdversePartyLiabilityPercent()
var ruleNumber = actions.ShortRuleName

if (totalExpLiability > 100) {
  claim.reject("newloss", 
               displaykey.Subrogation.Validation.Claim.LiabExceedsAdOnly(ruleNumber,totalExpLiability), null, null)
} else {
  if (claim.FaultRating == "1"){
    totalExpLiability = totalExpLiability + claim.Fault
    if (totalExpLiability > 100) {
      claim.reject("newloss", 
                   displaykey.Subrogation.Validation.Claim.LiabExceedsAdPlusIns(ruleNumber,totalExpLiability), null, null)
    }
  }
}
/*end00rule*/

  }
}
