package gw.sampledata
uses gw.pl.persistence.core.Bundle
uses gw.api.util.CurrencyUtil
uses gw.api.databuilder.ServiceRequestChangeBuilder
uses gw.api.databuilder.ServiceRequestBuilder

@Export
class SampleRobertFarleyClaim extends SampleDataBase {

  construct(inCache : SampleDataCache) {
    super(inCache)
  }

  override property get Description() : String {
    return "Robert Farley Personal Auto Claim and associated Contacts, Policy, Exposures, Notes, ClaimContacts, Activities and Financials"
  }
   
  override function testSampleData(bundle : Bundle) {
    create(bundle)
  }
     
  function create(bundle : Bundle) : ClaimInfo {

    var contactDemoSample3024 = new gw.api.databuilder.PersonBuilder()
      .withLastName("Farley")
      .withPublicId("demo_sample:3024")
      .withFirstName("Robert")
      .withPrimaryPhone("work")
      .withPrimaryAddressSetEarly( new gw.api.databuilder.AddressBuilder()
        .withAddressLine1("503 2nd Ave.")
        .withCountry("US")
        .withPostalCode("92101")
        .withState(State.TC_CA)
        .withAddressType("home")
        .withCity("San Diego"))
      .withWorkPhone("619-275-2346")
      .create(bundle)

    var contactDemoSample9 = new gw.api.databuilder.PersonBuilder()
      .withLastName("Weeks")
      .withPublicId("demo_sample:9")
      .withFirstName("William")
      .withPrimaryPhone("work")
      .withPrimaryAddressSetEarly( new gw.api.databuilder.AddressBuilder()
        .withAddressLine1("345 Fir Lane")
        .withCountry("US")
        .withPostalCode("91352")
        .withState(State.TC_CA)
        .withAddressType("home")
        .withCity("La Canada"))
      .withWorkPhone("619-275-5986")
      .create(bundle)

    var contactDemoSample10011 = new gw.api.databuilder.PersonBuilder()
      .withLastName("Egertson")
      .withPublicId("demo_sample:10011")
      .withFirstName("Karen")
      .withPrimaryPhone("work")
      .withPrimaryAddressSetEarly( new gw.api.databuilder.AddressBuilder()
        .withAddressLine1("908 Angels Landing Rd.")
        .withCountry("US")
        .withPostalCode("91352")
        .withState(State.TC_CA)
        .withAddressType("home")
        .withCity("Anaheim"))
      .withWorkPhone("213-457-6378")
      .create(bundle)

    var contactDemoSampleAutoShop1 = new gw.api.databuilder.AutoRepairShopBuilder()
            .withName("Joe's Auto Body Shop")
            .withPrimaryPhone("work")
            .withPrimaryAddressSetEarly( new gw.api.databuilder.AddressBuilder()
              .withAddressLine1("6246 Rock Ave")
              .withCountry("US")
              .withPostalCode("91006")
              .withState(State.TC_CA)
              .withAddressType("home")
              .withCity("Arcadia"))
            .withWorkPhone("579-628-5555")
            .create(bundle)
            
    var contactDemoSampleAutoShop2 = new gw.api.databuilder.AutoRepairShopBuilder()
            .withName("Frank's Car Repair")
            .withPrimaryPhone("work")
            .withPrimaryAddressSetEarly( new gw.api.databuilder.AddressBuilder()
              .withAddressLine1("456 Stone Ave")
              .withCountry("US")
              .withPostalCode("91006")
              .withState(State.TC_CA)
              .withAddressType("home")
              .withCity("Arcadia"))
            .withWorkPhone("579-628-4444")
            .create(bundle)

    var claim = new gw.api.databuilder.ClaimBuilder()
      .withIncidentReport(false)
      .withWeather("CL")
      .withAssignmentStatus("assigned")
      .withLossDate(BaseDate.addDays(-8))
      .withCurrency(gw.api.util.CurrencyUtil.getDefaultCurrency())
      .withStrategy("auto_normal")
      .withAssignmentDate(BaseDate.addDays(0))
      .withFlagged("neverflagged")
      .withLossLocation(new gw.api.databuilder.AddressBuilder()
        .withAddressLine1("506 2nd Ave.")
        .withCountry("US")
        .withPostalCode("92101")
        .withState(State.TC_CA)
        .withAddressType("home")
        .withCity("San Diego"))
      .withLossCause("vehcollision")
      .withClaimNumber("235-53-365889")
      .withMainContactType("self")
      .withReportedByType("other")
      .withLossType("AUTO")
      .withValidationLevel("newloss")
      .withPolicy( new gw.api.databuilder.PolicyBuilder()
        .withExpirationDate(BaseDate.addDays(274))
        .withUnderwritingCo("parent")
        .withVerified(true)
        .withOrigEffectiveDate(BaseDate.addDays(-3266))
        .withAccount("Account 1")
        .withCurrency(gw.api.util.CurrencyUtil.getDefaultCurrency())
        .withUnderwritingGroup("acme_auto")
        .withEffectiveDate(BaseDate.addDays(-90))
        .withStatus("inforce")
        .withPolicyNumber("54-586734")
        .withPublicId("demo_sample:8")
        .withTotalProperties(0)
        .withPolicyType("PersonalAuto")
        .withTotalVehicles(1)
        .withRiskUnit( new gw.api.databuilder.VehicleRUBuilder()
          .withRUNumber(1)
          .withVehicle( new gw.api.databuilder.VehicleBuilder()
            .withYear(2002)
            .withLicensePlate("2GDH967")
            .withPublicId("demo_sample:18")
            .withMake("Pontiac")
            .withState(Jurisdiction.TC_CA)
            .withModel("Grand Prix")
            .withVin("3DGF78575GD891525"))
          .withCoverage( new gw.api.databuilder.VehicleCoverageBuilder()
            .withIncidentLimit(20000bd.ofDefaultCurrency())
            .withType("PACollisionCov")
            .withDeductible(0bd.ofDefaultCurrency()))
          .withCoverage( new gw.api.databuilder.VehicleCoverageBuilder()
            .withIncidentLimit(20000bd.ofDefaultCurrency())
            .withType("PAComprehensiveCov")
            .withDeductible(0bd.ofDefaultCurrency()))
          .withCoverage(new gw.api.databuilder.VehicleCoverageBuilder()
            .withIncidentLimit(300000bd.ofDefaultCurrency())
            .withType("PALiabilityCov")
            .withExposureLimit(150000bd.ofDefaultCurrency()))
          .withCoverage( new gw.api.databuilder.VehicleCoverageBuilder()
            .withIncidentLimit(1000bd.ofDefaultCurrency())
            .withType("PAMedPayCov"))
          .withCoverage( new gw.api.databuilder.VehicleCoverageBuilder()
            .withIncidentLimit(1000bd.ofDefaultCurrency())
            .withType(CoverageType.TC_PATOWINGLABORCOV)))
        .withContactInRole(contactDemoSample3024, "insured")
        .withContactInRole(contactDemoSample10011, "agent"))
      .withFault(80)
      .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
      .withJurisdictionState("CA")
      .withSegment("auto_mid")
      .withReportedDate(BaseDate.addDays(-3))
      .withCoverageInQuestion(false)
      .withLOBCode("PersonalAutoLine")
      .withPublicID("demo_sample:20")
      .withDescription("Insured swerved to avoid an animal, struck claimant's car head-on")
      .withState("open")
      .withAssignedUser(findUserByUserName("aapplegate"))
      .withContactInRole(contactDemoSample9, "checkpayee")
      .withContactInRole(contactDemoSample3024, "maincontact")
      .withContactInRole(contactDemoSample9, "reporter")
      .withContactInRole(contactDemoSampleAutoShop1, ContactRole.TC_SERVICEREQUESTSPECIALIST)
      .withContactInRole(contactDemoSampleAutoShop2, ContactRole.TC_SERVICEREQUESTSPECIALIST)
      .withServiceRequest(new ServiceRequestBuilder()
        .withRequestedQuoteCompletionDate(BaseDate.addDays(14))
        .withExpectedQuoteCompletionDate(BaseDate.addDays(14))
        .withInstruction(gw.api.databuilder.ServiceRequestInstructionBuilder.uiReady())
        .withProgress(ServiceRequestProgress.TC_DRAFT)
        .withKind(ServiceRequestKind.TC_QUOTEANDSERVICE)
        .withQuoteStatus(ServiceRequestQuoteStatus.TC_NOQUOTE)
        .withInstruction(new gw.api.databuilder.ServiceRequestInstructionBuilder()
          .withCustomerContact(contactDemoSample3024)
          .withSpecialistService(SampleSpecialistServicesBase.AutoRepairBody)
          .withInstructionText("The insured prefers to be contacted by email")
          .withServiceAddress(contactDemoSampleAutoShop1.AddressOwner.Address))
        .withSpecialistCommMethod(SpecialistCommMethod.TC_GWPORTAL)
        .withSpecialist(contactDemoSampleAutoShop1)
        .withPublicId("demo_sample:1")
        .withAssignedUserAndDefaultGroup(AndyApplegate))
      .withServiceRequest(new ServiceRequestBuilder()
        .withRequestedServiceCompletionDate(BaseDate.addDays(7))
        .withExpectedServiceCompletionDate(BaseDate.addDays(7))
        .withProgress(ServiceRequestProgress.TC_DRAFT)
        .withQuoteStatus(ServiceRequestQuoteStatus.TC_NOQUOTE)
        .withKind(ServiceRequestKind.TC_SERVICEONLY)
        .withInstruction(new gw.api.databuilder.ServiceRequestInstructionBuilder()
          .withCustomerContact(contactDemoSample9)
          .withSpecialistService(SampleSpecialistServicesBase.AutoRepairGlass)
          .withInstructionText("The claimant prefers to be contacted by email")
          .withServiceAddress(contactDemoSampleAutoShop2.AddressOwner.Address))
        .withSpecialistCommMethod(SpecialistCommMethod.TC_GWPORTAL)
        .withSpecialist(contactDemoSampleAutoShop2)
        .withPublicId("demo_sample:2")
        .withAssignedUserAndDefaultGroup(AndyApplegate))
      .withNote( new gw.api.databuilder.NoteBuilder()
        .withTopic("general")
        .withAuthoringDate(BaseDate.addDays(-2))
        .withSubject("Initial phone call with insured")
        .withAuthor(findUserByUserName("cclark"))
        .withBody("Insured claims he swerved to avoid a dog in the road, then hit an oncoming car in the other lane."))
      .withNote( new gw.api.databuilder.NoteBuilder()
        .withTopic("general")
        .withAuthoringDate(BaseDate.addDays(-1))
        .withSubject("Initial phone call with claimant")
        .withAuthor(findUserByUserName("aapplegate"))
        .withBody("Spoke to claimant - he was hospitalized due to a fracture in a bone behind his eye and is under observation, and may need to undergo surgery.  Because claimant does not have other insurance, authorized a check to cover vehicle towing and initial hospital stay."))
      .withActivity( new gw.api.databuilder.ActivityBuilder()
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-3))
        .withEscalated(false)
        .withRecurring(false)
        .withImportance("notOnCalendar")
        .withCloseDate(BaseDate.addDays(-1))
        .withMandatory(true)
        .withPriority("high")
        .withActivityClass("task")
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withType("general")
        .withEscalationDate(BaseDate.addDays(4))
        .withStatus("complete")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withActivityPattern(findActivityPatternByCode("contact_insured"))
        .withSubject("Contact insured")
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withTargetDate(BaseDate.addDays(-1)))
      .withActivity( new gw.api.databuilder.ActivityBuilder()
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-3))
        .withEscalated(false)
        .withRecurring(false)
        .withImportance("notOnCalendar")
        .withCloseDate(BaseDate.addDays(-1))
        .withMandatory(true)
        .withPriority("high")
        .withActivityClass("task")
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withType("general")
        .withEscalationDate(BaseDate.addDays(4))
        .withStatus("complete")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withActivityPattern(findActivityPatternByCode("contact_claimant"))
        .withSubject("Contact claimant")
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withTargetDate(BaseDate.addDays(-1)))
      .withActivity( new gw.api.databuilder.ActivityBuilder()
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-3))
        .withEscalated(false)
        .withRecurring(false)
        .withImportance("notOnCalendar")
        .withMandatory(false)
        .withPriority("normal")
        .withActivityClass("task")
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withType("general")
        .withEscalationDate(BaseDate.addDays(17))
        .withStatus("open")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withActivityPattern(findActivityPatternByCode("initial_30day_review"))
        .withSubject("10 day review")
        .withAssignedUser(findUserByUserName("ssmith"))
        .withTargetDate(BaseDate.addDays(7)))
      .withActivity( new gw.api.databuilder.ActivityBuilder()
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-3))
        .withEscalated(false)
        .withRecurring(false)
        .withImportance("notOnCalendar")
        .withCloseDate(BaseDate.addDays(0))
        .withMandatory(true)
        .withPriority("high")
        .withActivityClass("task")
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withType("general")
        .withEscalationDate(BaseDate.addDays(10))
        .withStatus("complete")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withActivityPattern(findActivityPatternByCode("coverage"))
        .withSubject("Check coverage")
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withTargetDate(BaseDate.addDays(0)))
      .withActivity( new gw.api.databuilder.ActivityBuilder()
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-3))
        .withEscalated(false)
        .withRecurring(false)
        .withImportance("notOnCalendar")
        .withMandatory(true)
        .withPriority("normal")
        .withActivityClass("task")
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withType("general")
        .withEscalationDate(BaseDate.addDays(19))
        .withStatus("open")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withActivityPattern(findActivityPatternByCode("general_reminder"))
        .withSubject("Set initial reserve")
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withTargetDate(BaseDate.addDays(4)))
      .create(bundle)

    var coverageForAggLimit = claim.Policy.RiskUnits.singleWhere( \ r -> r.RUNumber == 1 ).Coverages.singleWhere(\ c -> c.Type == "PALiabilityCov")

    var robertFarleyClaimInfo = new gw.api.databuilder.ClaimInfoBuilder()
      .withRootPublicId("demo_sample:20")
      .withClaimNumber("235-53-365889")
      .onClaim(claim)
      .create(bundle)

    var policyPeriodDemoSample70008 = new gw.api.databuilder.PolicyPeriodBuilder()
      .withPolicy(new gw.api.databuilder.PeriodPolicyBuilder().onClaimInfo(robertFarleyClaimInfo))
      .withPolicyPeriodType("policy")
      .withExpirationDate(BaseDate.addDays(274))
      .withPolicyNumber("54-586734")
      .withPublicId("demo_sample:70008")
      .withPolicyType("PersonalAuto")
      .withEffectiveDate(BaseDate.addDays(-90))
      .create(bundle)

    var aggregateLimitDemoSample90002 = new gw.api.databuilder.AggregateLimitBuilder()
      .withLimitCurrencyAmount(300000bd.ofDefaultCurrency())
      .withCoverageLine( new gw.api.databuilder.CoverageLineLimitBuilder()
        .withCoverageLine( new gw.api.databuilder.CoverageLineBuilder()
          .withExposureUnitNumber(1)
          .withCoverageType("PALiabilityCov")
          .withCoverageSubtype("VehicleCoverage")
          .withCoverage(coverageForAggLimit)
          .onPolicyPeriod(policyPeriodDemoSample70008)) )
      .withPublicId("demo_sample:90002")
      .withLimitType("lossdate")
      .onPolicyPeriod(policyPeriodDemoSample70008)
      .create(bundle)

    var exposureDemoSample10003 = new gw.api.databuilder.ExposureBuilder()
      .withOtherCoverage(false)
      .withLossParty("insured")
      .withExposureType("VehicleDamage")
      .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
      .withAssignmentStatus("assigned")
      .withStrategy("auto_fast")
      .withProgress("investigation")
      .withJurisdictionState("CA")
      .withAssignmentDate(BaseDate.addDays(0))
      .withPrimaryCoverage("PACollisionCov")
      .withSegment("auto_low")
      .withClaimantType("insured")
      .withClaimOrder(1)
      .withPublicID("demo_sample:10003")
      .withState("open")
      .withAssignedUser(findUserByUserName("aapplegate"))
      .onClaim(claim)
      .withCoverageSubType("PACollisionCov")
      .withIncident( new gw.api.databuilder.VehicleIncidentBuilder()
        .withSpeed(40)
        .withSeverity("moderate-auto")
        .withCollisionPoint("front")
        .withDriverRelation("self")
        .withDescription("Damage to bumper and front panels")
        .withVehicle( new gw.api.databuilder.VehicleBuilder()
          .withYear(1993)
          .withLicensePlate("7FDG745")
          .withPublicId("demo_sample:8")
          .withMake("Mercury")
          .withState(Jurisdiction.TC_CA)
          .withModel("Sable")
          .withVin("6GYF54637HD645370"))
        .withOwnersPermission(true)
        .withContactInRole(contactDemoSample3024, "driver"))
      .withContactInRole(contactDemoSample3024, "claimant")
      .create(bundle)

    var exposureDemoSample10004 = new gw.api.databuilder.ExposureBuilder()
      .withOtherCoverage(false)
      .withLossParty("third_party")
      .withExposureType("VehicleDamage")
      .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
      .withAssignmentStatus("assigned")
      .withStrategy("auto_normal")
      .withProgress("investigation")
      .withJurisdictionState("CA")
      .withAssignmentDate(BaseDate.addDays(0))
      .withPrimaryCoverage("PALiabilityCov")
      .withSegment("auto_mid")
      .withClaimantType("veh_other_owner")
      .withClaimOrder(2)
      .withPublicID("demo_sample:10004")
      .withState("open")
      .withAssignedUser(findUserByUserName("aapplegate"))
      .onClaim(claim)
      .withCoverageSubType("PALiabilityCov_vd")
      .withIncident( new gw.api.databuilder.VehicleIncidentBuilder()
        .withSpeed(30)
        .withSeverity("major-auto")
        .withCollisionPoint("front")
        .withDriverRelation("self")
        .withDescription("Severely crumpled front end, not driveable")
        .withVehicle( new gw.api.databuilder.VehicleBuilder()
          .withYear(2003)
          .withLicensePlate("2GDH967")
          .withPublicId("demo_sample:12")
          .withMake("BMW")
          .withState(Jurisdiction.TC_CA)
          .withModel("355i")
          .withVin("3DGF78575GD892534"))
        .withOwnersPermission(true)
        .withContactInRole(contactDemoSample9, "driver"))
      .withContactInRole(contactDemoSample9, "claimant")
      .create(bundle)

    var exposureDemoSample20003 = new gw.api.databuilder.ExposureBuilder()
      .withOtherCoverage(false)
      .withLossParty("third_party")
      .withExposureType("BodilyInjuryDamage")
      .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
      .withAssignmentStatus("assigned")
      .withStrategy("injury_normal")
      .withProgress("investigation")
      .withJurisdictionState("CA")
      .withAssignmentDate(BaseDate.addDays(0))
      .withPrimaryCoverage("PALiabilityCov")
      .withSegment("injury_mid")
      .withClaimantType("veh_other_owner")
      .withClaimOrder(3)
      .withPublicID("demo_sample:20003")
      .withState("open")
      .withAssignedUser(findUserByUserName("aapplegate"))
      .onClaim(claim)
      .withCoverageSubType("PALiabilityCov_bi")
      .withIncident( new gw.api.databuilder.InjuryIncidentBuilder()
        .withGeneralInjuryType("specific")
        .withSeverity("major-injury")
        .withDescription("Bruises and lacerations to face and neck, broken orbital bone, potential vision loss")
        .withMedicalTreatmentType("hospital")
        .withDetailedInjuryType("58")
        .withLostWages(true)
        .withBodyPart( new gw.api.databuilder.BodyPartDetailsBuilder()
          .withPrimaryBodyPart("head")
          .withAppropriateDetailedBodyPart()
          .withOrdering(100))
        .withContactInRole(contactDemoSample9, "injured"))
      .withContactInRole(contactDemoSample9, "claimant")
      .create(bundle)

    var transactionSetDemoSample20006 = new gw.api.databuilder.CheckSetBuilder()
      .withApprovalDate(BaseDate.addDays(-7))
      .withRequestingUser(findUserByUserName("aapplegate"))
      .withApprovalStatus("approved")
      .onClaim(claim)
      .create(bundle)

    var transactionSetDemoSample20007 = new gw.api.databuilder.ReserveSetBuilder()
      .withApprovalDate(BaseDate.addDays(-2))
      .withRequestingUser(findUserByUserName("aapplegate"))
      .withApprovalStatus("approved")
      .onClaim(claim)
      .create(bundle)

    var reserveLineDemoSample14 = new gw.api.databuilder.ReserveLineBuilder()
      .withExposure(exposureDemoSample10003)
      .withCostType("claimcost")
      .withCostCategory("body")
      .withClaim(claim)
      .create(bundle)

    var reserveLineDemoSample15 = new gw.api.databuilder.ReserveLineBuilder()
      .withExposure(exposureDemoSample10004)
      .withCostType("claimcost")
      .withCostCategory("body")
      .withClaim(claim)
      .create(bundle)

    var reserveLineDemoSample16 = new gw.api.databuilder.ReserveLineBuilder()
      .withExposure(exposureDemoSample20003)
      .withCostType("claimcost")
      .withCostCategory("medical")
      .withClaim(claim)
      .create(bundle)

    var checkDemoSample10106 = new gw.api.databuilder.CheckBuilder()
      .onClaim(claim)
      .withIssueDate(BaseDate.addDays(-6))
      .withScheduledSendDate(BaseDate.addDays(-6))
      .withBankAccount("default")
      .onCheckSet(transactionSetDemoSample20006)
      .withPayTo("William Weeks")
      .withStatus("issued")
      .withPaymentMethod("check")
      .withCheckNumber("11059")
      .withPayee(new gw.api.databuilder.CheckPayeeBuilder()
            .withPayee(contactDemoSample9)
            .withPayeeType("claimant"))
      .withType("primary")
      .create(bundle)

    var transactionDemoSample10016 = new gw.api.databuilder.ReserveBuilder()
      .withReserveLine(reserveLineDemoSample14)
      .onExposure(exposureDemoSample10003)
      .onTransactionSet(transactionSetDemoSample20007)
      .withCostType("claimcost")
      .withCostCategory("body")
      .withCurrency(gw.api.util.CurrencyUtil.getDefaultCurrency())
      .withStatus("submitted")
      .onClaim(claim)
      .withTransToClaimExchangeRate(CurrencyUtil.isSingleCurrencyMode() ? null : gw.api.database.Query.make(entity.ExchangeRate).compare("PriceCurrency", Equals, Currency.TC_USD).compare("BaseCurrency", Equals, Currency.TC_USD).select().FirstResult)
      .withLineItem( new gw.api.databuilder.TransactionLineItemBuilder()
        .withComments("Repairs")
        .withClaimForExAmount(0bd.ofDefaultCurrency())
        .withReportingAmount(2500bd.ofDefaultCurrency())
        .withClaimAmount(2500bd.ofDefaultCurrency())
        .withReservingAmount(2500bd.ofDefaultCurrency())
        .withTransactionAmount(2500bd.ofDefaultCurrency())
        .withLineCategory("other")
        .withReportingForExAmount(0bd.ofDefaultCurrency()))
      .create(bundle)

    var transactionDemoSample10017 = new gw.api.databuilder.ReserveBuilder()
      .withReserveLine(reserveLineDemoSample15)
      .onExposure(exposureDemoSample10004)
      .onTransactionSet(transactionSetDemoSample20007)
      .withCostType("claimcost")
      .withCostCategory("body")
      .withCurrency(gw.api.util.CurrencyUtil.getDefaultCurrency())
      .withStatus("submitted")
      .onClaim(claim)
      .withTransToClaimExchangeRate(CurrencyUtil.isSingleCurrencyMode() ? null : gw.api.database.Query.make(entity.ExchangeRate).compare("PriceCurrency", Equals, Currency.TC_USD).compare("BaseCurrency", Equals, Currency.TC_USD).select().FirstResult)
      .withLineItem( new gw.api.databuilder.TransactionLineItemBuilder()
        .withComments("Repairs")
        .withClaimForExAmount(0bd.ofDefaultCurrency())
        .withReportingAmount(5000bd.ofDefaultCurrency())
        .withClaimAmount(5000bd.ofDefaultCurrency())
        .withReservingAmount(5000bd.ofDefaultCurrency())
        .withTransactionAmount(5000bd.ofDefaultCurrency())
        .withLineCategory("other")
        .withReportingForExAmount(0bd.ofDefaultCurrency()))
      .create(bundle)

    var transactionDemoSample10018 = new gw.api.databuilder.ReserveBuilder()
      .withReserveLine(reserveLineDemoSample16)
      .onExposure(exposureDemoSample20003)
      .onTransactionSet(transactionSetDemoSample20007)
      .withCostType("claimcost")
      .withCostCategory("medical")
      .withCurrency(gw.api.util.CurrencyUtil.getDefaultCurrency())
      .withStatus("submitted")
      .onClaim(claim)
      .withTransToClaimExchangeRate(CurrencyUtil.isSingleCurrencyMode() ? null : gw.api.database.Query.make(entity.ExchangeRate).compare("PriceCurrency", Equals, Currency.TC_USD).compare("BaseCurrency", Equals, Currency.TC_USD).select().FirstResult)
      .withLineItem( new gw.api.databuilder.TransactionLineItemBuilder()
        .withComments("Initial hospitalization costs")
        .withClaimForExAmount(0bd.ofDefaultCurrency())
        .withReportingAmount(12000bd.ofDefaultCurrency())
        .withClaimAmount(12000bd.ofDefaultCurrency())
        .withReservingAmount(12000bd.ofDefaultCurrency())
        .withTransactionAmount(12000bd.ofDefaultCurrency())
        .withLineCategory("doctor")
        .withReportingForExAmount(0bd.ofDefaultCurrency()))
      .create(bundle)

    var transactionDemoSample20014 = new gw.api.databuilder.PaymentBuilder()
      .withReserveLine(reserveLineDemoSample15)
      .onTransactionSet(transactionSetDemoSample20006)
      .withCostCategory("body")
      .withCurrency(gw.api.util.CurrencyUtil.getDefaultCurrency())
      .withStatus("submitted")
      .withTransToClaimExchangeRate(CurrencyUtil.isSingleCurrencyMode() ? null : gw.api.database.Query.make(entity.ExchangeRate).compare("PriceCurrency", Equals, Currency.TC_USD).compare("BaseCurrency", Equals, Currency.TC_USD).select().FirstResult)
      .onCheck(checkDemoSample10106)
      .withPaymentType("partial")
      .onExposure(exposureDemoSample10004)
      .withCostType("claimcost")
      .onClaim(claim)
      .withLineItem( new gw.api.databuilder.TransactionLineItemBuilder()
        .withComments("Towing and inspection")
        .withClaimForExAmount(0bd.ofDefaultCurrency())
        .withReportingAmount(300bd.ofDefaultCurrency())
        .withClaimAmount(300bd.ofDefaultCurrency())
        .withReservingAmount(300bd.ofDefaultCurrency())
        .withTransactionAmount(300bd.ofDefaultCurrency())
        .withLineCategory("other")
        .withReportingForExAmount(0bd.ofDefaultCurrency()))
      .create(bundle)

    var transactionDemoSample20015 = new gw.api.databuilder.PaymentBuilder()
      .withReserveLine(reserveLineDemoSample16)
      .onTransactionSet(transactionSetDemoSample20006)
      .withCostCategory("medical")
      .withCurrency(gw.api.util.CurrencyUtil.getDefaultCurrency())
      .withStatus("submitted")
      .withTransToClaimExchangeRate(CurrencyUtil.isSingleCurrencyMode() ? null : gw.api.database.Query.make(entity.ExchangeRate).compare("PriceCurrency", Equals, Currency.TC_USD).compare("BaseCurrency", Equals, Currency.TC_USD).select().FirstResult)
      .onCheck(checkDemoSample10106)
      .withPaymentType("partial")
      .onExposure(exposureDemoSample20003)
      .withCostType("claimcost")
      .onClaim(claim)
      .withLineItem( new gw.api.databuilder.TransactionLineItemBuilder()
        .withComments("Initial hospitalization and examination")
        .withClaimForExAmount(0bd.ofDefaultCurrency())
        .withReportingAmount(9000bd.ofDefaultCurrency())
        .withClaimAmount(9000bd.ofDefaultCurrency())
        .withReservingAmount(9000bd.ofDefaultCurrency())
        .withTransactionAmount(9000bd.ofDefaultCurrency())
        .withLineCategory("doctor")
        .withReportingForExAmount(0bd.ofDefaultCurrency()))
      .create(bundle)
    
    var doc1 = new gw.api.databuilder.DocumentBuilder()
          .onClaim(claim)
          .withName("AutoRepairEstimate")
          .withType(DocumentType.TC_REPAIRESTIMATE)
          .withStatus(DocumentStatusType.TC_APPROVING)
          .withAuthor("ClaimCenter")
          .withDateModified(BaseDate)
          .create(bundle)
     
    var serviceRequests = claim.ServiceRequests.toList().orderBy(\ s -> s.PublicID)
    
    // transition to instructed/record transition
    serviceRequests[0].Progress = ServiceRequestProgress.TC_REQUESTED
    serviceRequests[0].QuoteStatus = ServiceRequestQuoteStatus.TC_WAITINGFORQUOTE
    // Record the change for the service request history
    ServiceRequestChangeBuilder
        .recordProgressAndQuoteStatusChange(
          :newProgress = ServiceRequestProgress.TC_REQUESTED,
          :newQuoteStatus = ServiceRequestQuoteStatus.TC_WAITINGFORQUOTE)
        .onServiceRequest(serviceRequests[0])
        .withDescription(displaykey.Web.ServiceRequest.StateTransition.Description.InstructionSubmitted)
        .withSequence(serviceRequests[0].LatestChange != null ? serviceRequests[0].LatestChange.Sequence + 1 : 1)
        .withTimestamp(BaseDate.addBusinessDays(2))
        .create(bundle)

    // transition to instructed/record transition
    serviceRequests[1].Progress = ServiceRequestProgress.TC_REQUESTED
    // Record the change for the service request history
    ServiceRequestChangeBuilder
        .recordProgressAndQuoteStatusChange(
          :newProgress = ServiceRequestProgress.TC_REQUESTED)
        .onServiceRequest(serviceRequests[1])
        .withDescription(displaykey.Web.ServiceRequest.StateTransition.Description.InstructionSubmitted)
        .withSequence(serviceRequests[1].LatestChange != null ? serviceRequests[1].LatestChange.Sequence + 1 : 1)
        .withTimestamp(BaseDate.addBusinessDays(1))
        .create(bundle)
    
    var quoteWithDocuments1 = new gw.api.databuilder.ServiceRequestQuoteBuilder()
              .onServiceRequest(serviceRequests[0])
              .withAmount(1750bd.ofDefaultCurrency())
              .withDescription("Repair quote")    
              .withDocument(doc1)
              .withStatementCreationTime(BaseDate)
              .withExpectedDaysToPerformService(5)
              .withReferenceNumber("abc-123")
              .create(bundle)
    serviceRequests[0].LatestQuote = quoteWithDocuments1
    serviceRequests[0].Progress = ServiceRequestProgress.TC_SPECIALISTWAITING
    serviceRequests[0].QuoteStatus = ServiceRequestQuoteStatus.TC_WAITINGFORAPPROVAL  
    
   // Record the change for adding a quote to the service request
   ServiceRequestChangeBuilder
       .recordProgressAndQuoteStatusChange(
          :newProgress = ServiceRequestProgress.TC_SPECIALISTWAITING,
          :newQuoteStatus = ServiceRequestQuoteStatus.TC_WAITINGFORAPPROVAL)
        .onServiceRequest(serviceRequests[0])
        .withTimestamp(BaseDate.addBusinessDays(3))
        .withDescription(displaykey.Web.ServiceRequest.StateTransition.Description.AddedQuoteWithReferenceNumber(quoteWithDocuments1.ReferenceNumber, quoteWithDocuments1.Amount))
        .withRelatedStatement(quoteWithDocuments1)
        .withOperation(TC_ADDQUOTE)
        .withSequence(serviceRequests[0].LatestChange != null ? serviceRequests[0].LatestChange.Sequence + 1 : 1)
        .create(bundle)
    
    var serviceRequestActivity11 = new gw.api.databuilder.ActivityBuilder()
        .onClaim(claim)
        .withActivityPatternByCode("appraisal_independent")
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-7))
        .withEscalated(false)
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withStatus("complete")
        .withCloseDate(BaseDate.addDays(-5))
        .withAutoGenerated(true)
        .withTargetDate(BaseDate.addDays(-5))
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withServiceRequest(serviceRequests[1])
        .create(bundle)
        
    var serviceRequestActivity12 = new gw.api.databuilder.ActivityBuilder()
        .onClaim(claim)
        .withActivityPatternByCode("quote")
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-5))
        .withMandatory(true)
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withStatus("complete")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withTargetDate(BaseDate.addDays(1))
        .withEscalationDate(BaseDate.addDays(-2))
        .withCloseDate(BaseDate.addDays(-4))
        .withServiceRequest(serviceRequests[1])
        .create(bundle)    
      
    var serviceRequestActivity13 = new gw.api.databuilder.ActivityBuilder()
        .onClaim(claim)
        .withActivityPatternByCode("review_quote")
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-4))
        .withEscalated(false)
        .withMandatory(true)
        .withPriority("high")
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withStatus("complete")
        .withTargetDate(BaseDate.addDays(-3))
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withAssignedUser(findUserByUserName("ssmith"))
        .withCloseDate(BaseDate.addDays(-3))        
        .withServiceRequest(serviceRequests[1])
        .create(bundle)
        
    var serviceRequestActivity14 = new gw.api.databuilder.ActivityBuilder()
        .onClaim(claim)
        .withActivityPatternByCode("vehicle_inspection")
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-3))
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withStatus("open")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withTargetDate(BaseDate.addDays(7))
        .withServiceRequest(serviceRequests[1])
        .create(bundle)    
        
    var serviceRequestActivity01 = new gw.api.databuilder.ActivityBuilder()
        .onClaim(claim)
        .withActivityPatternByCode("appraisal_independent")
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(-1))
        .withEscalated(false)
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withStatus("complete")
        .withCloseDate(BaseDate.addDays(1))
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withTargetDate(BaseDate.addDays(1))
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withServiceRequest(serviceRequests[0])
        .create(bundle)
        
    var serviceRequestActivity02 = new gw.api.databuilder.ActivityBuilder()
        .onClaim(claim)
        .withActivityPatternByCode("quote")
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(1))
        .withMandatory(true)
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withStatus("complete")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withTargetDate(BaseDate.addDays(3))
        .withEscalationDate(BaseDate.addDays(4))
        .withCloseDate(BaseDate.addDays(3))
        .withServiceRequest(serviceRequests[0])
        .create(bundle)    
      
    var serviceRequestActivity03 = new gw.api.databuilder.ActivityBuilder()
        .onClaim(claim)
        .withActivityPatternByCode("review_quote")
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(3))
        .withEscalationDate(BaseDate.addDays(5))
        .withTargetDate(BaseDate.addDays(4))
        .withEscalated(false)
        .withMandatory(true)
        .withPriority("high")
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withStatus("open")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withAssignedUser(findUserByUserName("ssmith"))
        .withServiceRequest(serviceRequests[0])
        .create(bundle)
        
    var serviceRequestActivity04 = new gw.api.databuilder.ActivityBuilder()
        .onClaim(claim)
        .withActivityPatternByCode("vehicle_inspection")
        .withAssignmentStatus("assigned")
        .withAssignmentDate(BaseDate.addDays(4))
        .withAssignedGroup(findGroupByName("Auto1 - TeamA"))
        .withStatus("open")
        .withAutoGenerated(true)
        .withLastViewedDate(BaseDate.addDays(-2415))
        .withAssignedUser(findUserByUserName("aapplegate"))
        .withTargetDate(BaseDate.addDays(12))
        .withServiceRequest(serviceRequests[0])
        .create(bundle)    
                
   var serviceRequestNote1 = new gw.api.databuilder.NoteBuilder()
        .onClaim(claim)
        .withTopic("general")
        .withAuthoringDate(BaseDate)
        .withSubject("phone call with vendor")
        .withAuthor(findUserByUserName("aapplegate"))
        .withBody("Frank called and said the mechanic assigned to the vehicle is out sick; will reassign and doesn't expect delays")
        .withServiceRequest(serviceRequests[1])
        .create(bundle)
        
   var serviceRequestNote2 = new gw.api.databuilder.NoteBuilder()
        .onClaim(claim)
        .withTopic("general")
        .withAuthoringDate(BaseDate.addDays(-1))
        .withSubject("claimant request")
        .withAuthor(findUserByUserName("aapplegate"))
        .withBody("Claimant requested this vendor because of their proximity to his workplace.")
        .withServiceRequest(serviceRequests[1])
        .create(bundle)

    return robertFarleyClaimInfo
  }
}
