package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TXV07000 - Default CheckSet Rules")
internal class TXV07000DefaultCheckSetRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    
/*start00rule*/
return transactionSet.Subtype == "CheckSet" 
and (transactionSet as CheckSet).PrimaryCheck.DeliveryMethod == "send"
and (transactionSet as CheckSet).PrimaryCheck.MailToAddress == null 
and (transactionSet as CheckSet).PrimaryCheck.PaymentMethod != "eft"
/*end00rule*/

  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {

/*start00rule*/
transactionSet.rejectSubField(
  (transactionSet as CheckSet).PrimaryCheck, "MailToAddress",
  "newloss", displaykey.Web.FNOLWizard.CheckReady.SendingErrorMessage,  null, null)
/*end00rule*/

  }
}
