package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CLV06000 - Policy original effective date")
internal class CLV06000Policyoriginaleffectivedate {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.Policy.OrigEffectiveDate != null
and claim.Policy.OrigEffectiveDate > claim.Policy.EffectiveDate
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
claim.rejectField("Policy.EffectiveDate",
                     "newloss",
                     displaykey.Rules.Validation.Claim.PolicyOriginalEffectiveDateLaterThanEffectiveDate,
                     null,
                     null)

/*end00rule*/

  }
}
