package A8Thread_Getting_Setting_Priority;

/* What is ThreadPriority
================================================================================

1. Every thread in java has some priority. It may be default priority generated by the JVM or
   customized priority provided by the programmer.

2. The valid range of Thread priorities is [ 1 to 10] where 1 is MIN_PRIORITY and 10 is
   MAX_PRIORITY.

3. Thread class defines the following constants to represent some standard priorities.

         Thread.MIN_PRIORITY--->1

         Thread.NORM_PRIORITY--->5

         Thread.MAX_PRIORITY---->10

4. Which of the following are valid and invalid

    0( invalid priority)
    1( valid priority)
    10( valid priority)

    Thread.LOW_PRIORITY( invalid)
    Thread.HIGH_PRIORITY(invalid)
    Thread.MIN_PRIORITY( valid)
    Thread.NORM_PRIORITY(valid).



5. Thread Scheduler will use the priorities while allocating the processor. The thread which is having the highest priority
   will get the chance first.


6. If 2 threads have the same priority then we cant expect exact execution order. It depends upon thread Scheduler.

*/

//----------------------------------------------------------------------**************---------------------------------------------------